n = str(input('Digite o seu nome completo: ')).strip()
nome = n.split()
print('Prazer em te conenhecer!')
print('Seu primeiro é {}'.format(nome[0]))
print(' Seu segundo nome é {}'.format(nome[len(nome)-1]))